### ISSUE TITLE
Cannot compile on Ubuntu 20.04 using the latest Eigen3 (3.3.7-2)

### ISSUE THREAD

**Issue by sebastienmascha** [isl-org/Open3D#5594]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
git clone --recursive https://github.com/isl-org/Open3D
cd Open3D
```

#### Then, I build Open3D (on Ubuntu 20.04, with CUDA 11.4.2) with:
```
sudo rm -rf build &&  sudo mkdir build && \
sudo cmake -S . -B build \
  -DBUILD_SHARED_LIBS=ON -DBUILD_PYTHON_MODULE=ON \
  -DPython3_ROOT=/usr/bin/python3 \
  -DUSE_SYSTEM_EIGEN3=ON && \
sudo cmake --build build -j10
```

### Error message

```shell
In file included from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/LegacyReconstructionUtil.h:31,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/OfflineReconstruction.cpp:28:
/home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/DebugUtil.h:40:2: error: no matching function for call to 'Eigen::Matrix<double, 4, 4>::Matrix(<brace-enclosed initializer list>)'
   40 | });
      |  ^
In file included from /usr/include/eigen3/Eigen/Core:458,
                 from /home/seb/dev/contributions/Open3D/cpp/open3d/camera/PinholeCameraIntrinsic.h:29,
                 from /home/seb/dev/contributions/Open3D/cpp/open3d/Open3D.h:31,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/FileSystemUtil.h:37,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/Config.h:31,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/OfflineReconstruction.cpp:27:
/usr/include/eigen3/Eigen/src/Core/Matrix.h:387:14: note: candidate: 'template<class OtherDerived> Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const Eigen::RotationBase<OtherDerived, Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::ColsAtCompileTime>&) [with OtherDerived = OtherDerived; _Scalar = double; int _Rows = 4; int _Cols = 4; int _Options = 0; int _MaxRows = 4; int _MaxCols = 4]'
  387 |     explicit Matrix(const RotationBase<OtherDerived,ColsAtCompileTime>& r);
      |              ^~~~~~
/usr/include/eigen3/Eigen/src/Core/Matrix.h:387:14: note:   template argument deduction/substitution failed:
In file included from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/LegacyReconstructionUtil.h:31,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/OfflineReconstruction.cpp:28:
/home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/DebugUtil.h:40:2: note:   couldn't deduce template parameter 'OtherDerived'
   40 | });
      |  ^
In file included from /usr/include/eigen3/Eigen/Core:458,
                 from /home/seb/dev/contributions/Open3D/cpp/open3d/camera/PinholeCameraIntrinsic.h:29,
                 from /home/seb/dev/contributions/Open3D/cpp/open3d/Open3D.h:31,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/FileSystemUtil.h:37,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/Config.h:31,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/OfflineReconstruction.cpp:27:
/usr/include/eigen3/Eigen/src/Core/Matrix.h:376:25: note: candidate: 'template<class OtherDerived> Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const Eigen::EigenBase<OtherDerived>&) [with OtherDerived = OtherDerived; _Scalar = double; int _Rows = 4; int _Cols = 4; int _Options = 0; int _MaxRows = 4; int _MaxCols = 4]'
  376 |     EIGEN_STRONG_INLINE Matrix(const EigenBase<OtherDerived> &other)
      |                         ^~~~~~
/usr/include/eigen3/Eigen/src/Core/Matrix.h:376:25: note:   template argument deduction/substitution failed:
In file included from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/LegacyReconstructionUtil.h:31,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/OfflineReconstruction.cpp:28:
/home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/DebugUtil.h:40:2: note:   couldn't deduce template parameter 'OtherDerived'
   40 | });
      |  ^
In file included from /usr/include/eigen3/Eigen/Core:458,
                 from /home/seb/dev/contributions/Open3D/cpp/open3d/camera/PinholeCameraIntrinsic.h:29,
                 from /home/seb/dev/contributions/Open3D/cpp/open3d/Open3D.h:31,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/FileSystemUtil.h:37,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/Config.h:31,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/OfflineReconstruction.cpp:27:
/usr/include/eigen3/Eigen/src/Core/Matrix.h:368:25: note: candidate: 'Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>&) [with _Scalar = double; int _Rows = 4; int _Cols = 4; int _Options = 0; int _MaxRows = 4; int _MaxCols = 4]'
  368 |     EIGEN_STRONG_INLINE Matrix(const Matrix& other) : Base(other)
      |                         ^~~~~~
/usr/include/eigen3/Eigen/src/Core/Matrix.h:368:46: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'const Eigen::Matrix<double, 4, 4>&'
  368 |     EIGEN_STRONG_INLINE Matrix(const Matrix& other) : Base(other)
      |                                ~~~~~~~~~~~~~~^~~~~
/usr/include/eigen3/Eigen/src/Core/Matrix.h:355:25: note: candidate: 'Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const Scalar&, const Scalar&, const Scalar&, const Scalar&) [with _Scalar = double; int _Rows = 4; int _Cols = 4; int _Options = 0; int _MaxRows = 4; int _MaxCols = 4; Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Scalar = double]'
  355 |     EIGEN_STRONG_INLINE Matrix(const Scalar& x, const Scalar& y, const Scalar& z, const Scalar& w)
      |                         ^~~~~~
/usr/include/eigen3/Eigen/src/Core/Matrix.h:355:25: note:   candidate expects 4 arguments, 1 provided
/usr/include/eigen3/Eigen/src/Core/Matrix.h:345:25: note: candidate: 'Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const Scalar&, const Scalar&, const Scalar&) [with _Scalar = double; int _Rows = 4; int _Cols = 4; int _Options = 0; int _MaxRows = 4; int _MaxCols = 4; Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Scalar = double]'
  345 |     EIGEN_STRONG_INLINE Matrix(const Scalar& x, const Scalar& y, const Scalar& z)
      |                         ^~~~~~
/usr/include/eigen3/Eigen/src/Core/Matrix.h:345:25: note:   candidate expects 3 arguments, 1 provided
/usr/include/eigen3/Eigen/src/Core/Matrix.h:299:25: note: candidate: 'template<class T0, class T1> Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const T0&, const T1&) [with T0 = T0; T1 = T1; _Scalar = double; int _Rows = 4; int _Cols = 4; int _Options = 0; int _MaxRows = 4; int _MaxCols = 4]'
  299 |     EIGEN_STRONG_INLINE Matrix(const T0& x, const T1& y)
      |                         ^~~~~~
/usr/include/eigen3/Eigen/src/Core/Matrix.h:299:25: note:   template argument deduction/substitution failed:
In file included from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/LegacyReconstructionUtil.h:31,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/OfflineReconstruction.cpp:28:
/home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/DebugUtil.h:40:2: note:   candidate expects 2 arguments, 1 provided
   40 | });
      |  ^
In file included from /usr/include/eigen3/Eigen/Core:458,
                 from /home/seb/dev/contributions/Open3D/cpp/open3d/camera/PinholeCameraIntrinsic.h:29,
                 from /home/seb/dev/contributions/Open3D/cpp/open3d/Open3D.h:31,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/FileSystemUtil.h:37,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/Config.h:31,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/OfflineReconstruction.cpp:27:
/usr/include/eigen3/Eigen/src/Core/Matrix.h:291:34: note: candidate: 'template<class T> Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const T&) [with T = T; _Scalar = double; int _Rows = 4; int _Cols = 4; int _Options = 0; int _MaxRows = 4; int _MaxCols = 4]'
  291 |     EIGEN_STRONG_INLINE explicit Matrix(const T& x)
      |                                  ^~~~~~
/usr/include/eigen3/Eigen/src/Core/Matrix.h:291:34: note:   template argument deduction/substitution failed:
In file included from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/LegacyReconstructionUtil.h:31,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/OfflineReconstruction.cpp:28:
/home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/DebugUtil.h:40:2: note:   couldn't deduce template parameter 'T'
   40 | });
      |  ^
In file included from /usr/include/eigen3/Eigen/Core:458,
                 from /home/seb/dev/contributions/Open3D/cpp/open3d/camera/PinholeCameraIntrinsic.h:29,
                 from /home/seb/dev/contributions/Open3D/cpp/open3d/Open3D.h:31,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/FileSystemUtil.h:37,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/Config.h:31,
                 from /home/seb/dev/contributions/Open3D/cpp/apps/OfflineReconstruction/OfflineReconstruction.cpp:27:
/usr/include/eigen3/Eigen/src/Core/Matrix.h:273:5: note: candidate: 'Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>&&) [with _Scalar = double; int _Rows = 4; int _Cols = 4; int _Options = 0; int _MaxRows = 4; int _MaxCols = 4]'
  273 |     Matrix(Matrix&& other) EIGEN_NOEXCEPT_IF(std::is_nothrow_move_constructible<Scalar>::value)
      |     ^~~~~~
/usr/include/eigen3/Eigen/src/Core/Matrix.h:273:21: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'Eigen::Matrix<double, 4, 4>&&'
  273 |     Matrix(Matrix&& other) EIGEN_NOEXCEPT_IF(std::is_nothrow_move_constructible<Scalar>::value)
      |            ~~~~~~~~~^~~~~
/usr/include/eigen3/Eigen/src/Core/Matrix.h:267:14: note: candidate: 'Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(Eigen::internal::constructor_without_unaligned_array_assert) [with _Scalar = double; int _Rows = 4; int _Cols = 4; int _Options = 0; int _MaxRows = 4; int _MaxCols = 4]'
  267 |     explicit Matrix(internal::constructor_without_unaligned_array_assert)
      |              ^~~~~~
/usr/include/eigen3/Eigen/src/Core/Matrix.h:267:21: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'Eigen::internal::constructor_without_unaligned_array_assert'
  267 |     explicit Matrix(internal::constructor_without_unaligned_array_assert)
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/eigen3/Eigen/src/Core/Matrix.h:259:25: note: candidate: 'Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix() [with _Scalar = double; int _Rows = 4; int _Cols = 4; int _Options = 0; int _MaxRows = 4; int _MaxCols = 4]'
  259 |     EIGEN_STRONG_INLINE Matrix() : Base()
      |                         ^~~~~~
/usr/include/eigen3/Eigen/src/Core/Matrix.h:259:25: note:   candidate expects 0 arguments, 1 provided
make[2]: *** [cpp/apps/CMakeFiles/OfflineReconstruction.dir/build.make:76: cpp/apps/CMakeFiles/OfflineReconstruction.dir/OfflineReconstruction/OfflineReconstruction.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3006: cpp/apps/CMakeFiles/OfflineReconstruction.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.8.10
- System architecture: x86
- Is this a remote workstation? no
- How did you install Open3D? build from source
- Compiler version (if built from source): gcc 10.3.0
```

### Additional information
The compilation works perfectly without the option `-DUSE_SYSTEM_EIGEN3=ON`. This option will skip the compilation from source of Eigen3 and will instead use the system installed version.

Nevertheless, there are many error messages using Eigen3 libeigen3-dev 3.3.7-2.

-- ================================================================================
-- Open3D 0.15.2 Configuration Summary
-- ================================================================================
-- Enabled Features:
--   OpenMP .................................. ON
--   Headless Rendering ...................... OFF
--   Azure Kinect Support .................... OFF
--   Intel RealSense Support ................. OFF
--   CUDA Support ............................ OFF
--   SYCL Support ............................ OFF
--   ISPC Support ............................ ON
--   Build GUI ............................... OFF
--   Build WebRTC visualizer ................. OFF
--   Build Shared Library .................... ON
--   Build Unit Tests ........................ OFF
--   Build Examples .......................... OFF
--   Build Python Module ..................... ON
--   Build Jupyter Extension ................. OFF
--   Build TensorFlow Ops .................... OFF
--   Build PyTorch Ops ....................... OFF
--   Build Benchmarks ........................ OFF
--   Bundle Open3D-ML ........................ OFF
--   Force GLIBCXX_USE_CXX11_ABI= ............ 0
-- ================================================================================
-- Third-Party Dependencies:
--   Assimp .................................. yes (build from source)
--   BLAS .................................... yes
--   Eigen3 .................................. yes (v3.3.7)
--   filament ................................ no
--   fmt ..................................... yes (build from source)
--   GLEW .................................... yes (build from source)
--   GLFW .................................... yes (build from source)
--   googletest .............................. no
--   imgui ................................... no
--   ippicv .................................. yes (build from source)
--   JPEG .................................... yes (build from source)
--   jsoncpp ................................. yes (build from source)
--   liblzf .................................. yes (build from source)
--   msgpack ................................. yes (build from source)
--   nanoflann ............................... yes (build from source)
--   OpenGL .................................. yes
--   PNG ..................................... yes (build from source)
--   qhullcpp ................................ yes (build from source)
--   librealsense ............................ no
--   TBB ..................................... yes (build from source)
--   tinyfiledialogs ......................... yes (build from source)
--   TinyGLTF ................................ yes (build from source)
--   tinyobjloader ........................... yes (build from source)
--   WebRTC .................................. no
--   ZeroMQ .................................. yes (build from source)
-- ================================================================================

**Comment by sebastienmascha** [comment]
This is a bug using the default `libeigen3-dev` version from APT.
Currently APT install  the version `3.3.7` on Ubuntu 20.04.
Therefore, you cannot use some new features like _initializer_list constructors to Matrix and Array_ etc...

Removing this version and compiling Eigen version `3.4` works perfectly. I will close the issue.
