### ISSUE TITLE
Error running SLAC

### ISSUE THREAD

**Issue by likui01** [isl-org/Open3D#4178]
Hi,
I am trying to reconstruct using following command
`python run_system.py /home/mlv/work/open3d/Open3D/examples/python/reconstruction_system/config/tutorial.json  --make --register --refine --integrate --slac --slac_integrate`

upto integration code work file, but when it start to compute SLAC it gives me following error.
`    active_buf_indices = hashmap.get_active_buf_indices().to(
AttributeError: 'open3d.cpu.pybind.core.Hashmap' object has no attribute 'get_active_buf_indices'`

how can i fix this error?

And there is folder new_reconstruction, which is its main file?

**Comment by saschandroid** [comment]
Hi!
After the fix I got 'same' error:

```
active_buf_indices = hashmap.active_buf_indices().to(
AttributeError: 'open3d.cpu.pybind.core.Hashmap' object has no attribute 'active_buf_indices'
```

I fixed the error by using the code from before the fix and changing only
`active_buf_indices = hashmap.active_buf_indices().to( o3d.core.Dtype.Int64)`
to
`active_buf_indices = hashmap.get_active_addrs().to(o3d.core.Dtype.Int64)`

**Comment by theNded** [comment]
@saschandroid Thanks for the feedback! This is due to an API change. Your version should work with `0.13`, but please use the `active_buf_indices` when you upgrade to the latest open3d (i.e. build from source or the pending 0.14).
