### ISSUE TITLE
Summarize the issue and your environments (e.g., "Cannot compile on Ubuntu 20.04 with OpenBLAS")

### ISSUE THREAD

**Issue by grewe** [isl-org/Open3D#7263]
### Checklist

- [x] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [x] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [x] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### using Google Colab environment --have followed getting started using
open3d
Version: 0.19.0
numpy
Version: 2.2.6
 pip
Version: 24.1.2

when attempt to import open3d get error:

`--------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-37-2bb78b04a701>](https://localhost:8080/#) in <cell line: 0>()
----> 1 import open3d as o3d

18 frames
[/usr/local/lib/python3.11/dist-packages/numpy/_core/strings.py](https://localhost:8080/#) in <module>
     12 from numpy._core.multiarray import _vec_string
     13 from numpy._core.overrides import set_module
---> 14 from numpy._core.umath import (
     15     isalpha,
     16     isdigit,

ImportError: cannot import name '_center' from 'numpy._core.umath' (/usr/local/lib/python3.11/dist-packages/numpy/_core/umath.py)
`

### Error message

```shell
ImportError Traceback (most recent call last)
in <cell line: 0>()
----> 1 import open3d as o3d

18 frames
/usr/local/lib/python3.11/dist-packages/numpy/_core/strings.py in
12 from numpy._core.multiarray import _vec_string
13 from numpy._core.overrides import set_module
---> 14 from numpy._core.umath import (
15 isalpha,
16 isdigit,

ImportError: cannot import name '_center' from 'numpy._core.umath' (/usr/local/lib/python3.11/dist-packages/numpy/_core/umath.py)
```

### Open3D, Python and System information

```markdown
- Google Colab with CPU
- Python version: Python 3.11
- Open3D version: output from python: 0.19
- System architecture: Google Colab -CPU?
- Is this a remote workstation?: yes 
- How did you install Open3D?: pip  
- Compiler version (if built from source): NA
```

### Additional information

I have tried to do older version combinations with open3D and numpy and that does not work either.  I do not know how to solve this issue.

**Comment by juanmigutierrez** [comment]
Try run this if it solves it, it worked for me
`!uv pip install numpy --upgrade`
