### PR TITLE
Remove unused import to allow async_event_loop to work without Open3D-ML

### LINKED ISSUE #4384: "Web visualizer" requires `tensorboard` and fails on `ImportError` from `open3d.ml.vis`
**Description**

The `draw` function from `open3d.web_visualizer` fails in version 0.14.1 - first on a `ModuleNotFoundError` when `tensorboard` is not installed, then an `ImportError` from `open3d.ml.vis` if `tensorboard` is installed. 

**How to reproduce**

1. Create Python 3.9 conda environment with JupyterLab
2. Install open3d version 0.14.1 either with conda or with pip
3. Create a Jupyter notebook and enter the following:

```python
import open3d as o3d
from open3d.web_visualizer import draw
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()
draw([mesh])
```

4. If tensorboard is not installed, get `ModuleNotFoundError: No module named 'tensorboard'`
5. Install `tensorboard` with pip
6. Rerun the notebook, get `ImportError: cannot import name 'Colormap' from 'open3d.ml.vis'`

**Expected behavior**

The same code worked in version 0.13.0.

**Environment:**

- Operating system: Windows 10 64-bit
- Python version: Python 3.9
- Open3D version: 0.14.1
- Same issue with conda and pip installation

**Additional context**

From what I understand, the following happens:
* `web_analyzer.py`:

https://github.com/isl-org/Open3D/blob/4dea5bebba34abea39dae6e11bb54e6ff320d6cf/python/open3d/web_visualizer.py#L34

* `visualization/async_event_loop.py`:

https://github.com/isl-org/Open3D/blob/4dea5bebba34abea39dae6e11bb54e6ff320d6cf/python/open3d/visualization/async_event_loop.py#L74

* `visualization/tensorboard_plugin/util.py`:
 
https://github.com/isl-org/Open3D/blob/4dea5bebba34abea39dae6e11bb54e6ff320d6cf/python/open3d/visualization/tensorboard_plugin/util.py#L34-L42

* `ml/vis.py`:

https://github.com/isl-org/Open3D/blob/4dea5bebba34abea39dae6e11bb54e6ff320d6cf/python/open3d/ml/vis.py#L30-L34

* `open3d.ml.vis` does not define anything because `_build_config['BUNDLE_OPEN3D_ML']` is `False`

Here are all the contents of `o3d._build_config`:

```python

{'BUILD_TENSORFLOW_OPS': False,
 'BUILD_PYTORCH_OPS': False,
 'BUILD_CUDA_MODULE': False,
 'BUILD_AZURE_KINECT': True,
 'BUILD_LIBREALSENSE': True,
 'BUILD_SHARED_LIBS': False,
 'BUILD_GUI': True,
 'ENABLE_HEADLESS_RENDERING': False,
 'BUILD_JUPYTER_EXTENSION': True,
 'BUNDLE_OPEN3D_ML': False,
 'GLIBCXX_USE_CXX11_ABI': False,
 'CMAKE_BUILD_TYPE': 'Release',
 'CUDA_VERSION': '',
 'CUDA_GENCODES': '',
 'Tensorflow_VERSION': '',
 'Pytorch_VERSION': '',
 'WITH_OPENMP': True,
 'WITH_FAISS': False}
 ```

### PR DESCRIPTION
**Pull request by ssheorey**
Resolves #4384

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4402)

### CODE REVIEW

**Comment by yxlao** [comment]
LGTM after CI passing.

There is still a CI error:
```
==================================== ERRORS ====================================
________ ERROR collecting test/visualization/test_tensorboard_plugin.py ________
python/test/visualization/test_tensorboard_plugin.py:36: in <module>
    BoundingBox3D = vis.BoundingBox3D
E   AttributeError: module 'open3d.ml.vis' has no attribute 'BoundingBox3D'
=========================== short test summary info ============================
ERROR python/test/visualization/test_tensorboard_plugin.py - AttributeError: ...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 6.06s ===============================
```

**Comment by ssheorey** [comment]
CI Tests pass now.

**Review by yxlao — APPROVED** [review]
