### PR TITLE
Use GLIBCXX_USE_CXX11_ABI by default

### LINKED ISSUE #2286: Errors occur when Open3D library is linked together with other libraries, e.g. gflags, opencv
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Errors occur when Open3D library is linked together with other libraries, e.g. gflags, opencv
**To Reproduce**

Please see 
https://github.com/bing-jian/open3d_test

**Expected behavior**
The code should compile and work on major platforms including Windows, macOS and linux.

**Environment (please complete the following information):**
- Operating system:
  OSX 10.15, Ubuntu 16.04 and 18.04, Windows 10 64-bit
- Open3D version:  
  0.10.0
- Is this remote workstation?: 
 no
- How did you install Open3D?:
 build from source
- Compiler version (if built from source):
 gcc 7.5, clang 11.0

**Additional context**
Same code also worked on Windows 10.

### LINKED ISSUE #3515: Open3d will make the functions related to polygon in pcl unable to be found
**Describe the bug**
When I compile the pcl and open3d programs separately, they both work. But when I try to compile the two together, it generates something like 
```
TestVisualizer.cpp:(.text+0x1b4): undefined reference to `pcl::io::loadPolygonFilePLY(std::string const&, pcl::PolygonMesh&)`
```
I have tried both "loadPLYFile" and "loadPolygonFilePLY", but they both failed.

**To Reproduce**
TestVisualizer.cpp
```
#include <pcl/PolygonMesh.h>
#include <pcl/io/ply_io.h>
#include <pcl/io/vtk_lib_io.h>
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>

#include <iostream>
#include <memory>
#include <thread>

#include "open3d/Open3D.h"

// A simplified version of examples/cpp/Visualizer.cpp to demonstrate linking
// an external project to Open3D.
int main(int argc, char *argv[]) {
  using namespace open3d;

  pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);

  if (pcl::io::loadPLYFile(argv[1], *cloud) == -1) {
    PCL_ERROR("Couldn't read the cloud. \n");
  }

  pcl::PolygonMesh::Ptr mesh(new pcl::PolygonMesh);

  if (pcl::io::loadPolygonFilePLY(argv[2], *mesh) == -1) {
    PCL_ERROR("Couldn't read the mesh. \n");
  }

  utility::SetVerbosityLevel(utility::VerbosityLevel::Debug);
  if (argc < 3) {
    utility::LogInfo("Open3D {}\n", OPEN3D_VERSION);
    utility::LogInfo("\n");
    utility::LogInfo("Usage:\n");
    utility::LogInfo("    > TestVisualizer [mesh|pointcloud] [filename]\n");
    // CI will execute this file without input files, return 0 to pass
    return 0;
  }

  std::string option(argv[1]);
  if (option == "mesh") {
    auto mesh_ptr = std::make_shared<geometry::TriangleMesh>();
    if (io::ReadTriangleMesh(argv[2], *mesh_ptr)) {
      utility::LogInfo("Successfully read {}\n", argv[2]);
    } else {
      utility::LogWarning("Failed to read {}\n\n", argv[2]);
      return 1;
    }
    mesh_ptr->ComputeVertexNormals();
    visualization::DrawGeometries({mesh_ptr}, "Mesh", 1600, 900);
  } else if (option == "pointcloud") {
    auto cloud_ptr = std::make_shared<geometry::PointCloud>();
    if (io::ReadPointCloud(argv[2], *cloud_ptr)) {
      utility::LogInfo("Successfully read {}\n", argv[2]);
    } else {
      utility::LogWarning("Failed to read {}\n\n", argv[2]);
      return 1;
    }
    cloud_ptr->NormalizeNormals();
    visualization::DrawGeometries({cloud_ptr}, "PointCloud", 1600, 900);
  } else {
    utility::LogWarning("Unrecognized option: {}\n", option);
    return 1;
  }
  utility::LogInfo("End of the test.\n");

  return 0;
}
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.12.0)
set (CMAKE_CXX_STANDARD 14)

project(TestVisualizer LANGUAGES C CXX)
set(CMAKE_INSTALL_PREFIX "/usr/include/open3d")
# Find installed Open3D, which exports Open3D::Open3D

set(Open3D_DIR /home/stereye/GitHub/Open3D/install/lib/cmake/Open3D)
find_package(Open3D)
find_package(PCL 1.10 REQUIRED)

if(NOT Open3D_FOUND)
    message(FATAL_ERROR "Open3D not found, please use -DCMAKE_INSTALL_PREFIX=open3d_install_dir")
endif()
include_directories(${PCL_INCLUDE_DIRS})
add_executable(TestVisualizer TestVisualizer.cpp)
target_link_libraries(TestVisualizer Open3D::Open3D ${PCL_LIBRARIES})
```

1. mkdir build
2. cd build
3. cmake ..
4. make -j8
5. See error

**Expected behavior**
Error message was like
```
/usr/bin/ld: CMakeFiles/TestVisualizer.dir/TestVisualizer.cpp.o: in function `main':
TestVisualizer.cpp:(.text+0x1b4): undefined reference to `pcl::io::loadPolygonFilePLY(std::string const&, pcl::PolygonMesh&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/TestVisualizer.dir/build.make:238: TestVisualizer] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/TestVisualizer.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
But if you comment out all of parts about open3d in TestVisualizer.cpp, and let it be
```
target_link_libraries(TestVisualizer ${PCL_LIBRARIES})
```
in CMakeLists.txt, it will be successfully compiled.

**Environment (please complete the following information):**

- Operating system: Ubuntu 20.04
- Open3D version: I don't know where to look for the version, it is the latest source on 05.28.2021
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): Cmake 3.20.3

### PR DESCRIPTION
**Pull request by QuentinTorg**
Set the GLIBCXX_USE_CXX11_ABI ON as default independent of the value of BUILD_SYCL_MODULE

## Type

-   [X] Bug fix (non-breaking change which fixes an issue): Fixes #2286, Fixes #3515
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

Previously the CXX11 ABI was off by default. #4387 was merged to fix this issue. Later, a regression was introduced with #5081 that made the default CXX11 ABI conditional on another variable. This once again changed the default CXX11 ABI back to the problematic case if no parameter was specified

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [X] I will follow up and update the code if CI fails.
    
-   [X] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

This PR removes the conditional check so that the CXX11 ABI will be used by default

- - -
This change is [Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6206)

### CODE REVIEW

**Review by ssheorey — APPROVED** [review]

**Comment by ssheorey** [comment]
Hi @QuentinTorg thanks for the bug fix!
