### ISSUE TITLE
Cannot compile on Ubuntu 24.04 with CUDA 12.6

### ISSUE THREAD

**Issue by Tiqo01** [isl-org/Open3D#7016]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I build Open3D (on Ubuntu 24.04, with CUDA 12.6) with:
```
mkdir build
cd build
cmake -DBUILD_CUDA_MODULE=ON  ..
make -j$(nproc)
```

### Error message

```shell
Open3D/build/stdgpu/include/stdgpu/impl/memory_detail.h(641): error: more than one instance of overloaded function "stdgpu::forward" matches the argument list:
            function template "_Tp &&cuda::std::__4::forward<_Tp>(cuda::std::__4::__libcpp_remove_reference_t<_Tp> &) noexcept" (declared at line 32 of /usr/local/cuda-12/targets/x86_64-linux/include/cuda/std/__utility/forward.h)
            function template "T &&stdgpu::forward<T>(std::remove_reference_t<T> &) noexcept" (declared at line 24 of Open3D/build/stdgpu/include/stdgpu/impl/utility_detail.h)
            argument types are: (const thrust::THRUST_200500_860_NS::pair<const open3d::utility::MiniVec<short, 4>, open3d::core::buf_index_t>)
      construct_at(p, forward<Args>(args)...);
                      ^
Open3D/build/stdgpu/include/stdgpu/impl/utility_detail.h(31): note #3326-D: function template "stdgpu::forward<T>(std::remove_reference_t<T> &&) noexcept" does not match because argument #1 does not match parameter
  forward(std::remove_reference_t<T>&& t) noexcept
  ^
/usr/local/cuda-12/targets/x86_64-linux/include/cuda/std/__utility/forward.h(39): note #3326-D: function template "cuda::std::__4::forward<_Tp>(cuda::std::__4::__libcpp_remove_reference_t<_Tp> &&) noexcept" does not match because argument #1 does not match parameter
  forward(__libcpp_remove_reference_t<_Tp>&& __t) noexcept

Open3D/build/stdgpu/include/stdgpu/impl/memory_detail.h(649): error: more than one instance of function template "stdgpu::destroy_at" matches the argument list:
            function template "void cuda::std::__4::destroy_at(_Tp *)" (declared at line 228 of /usr/local/cuda-12/targets/x86_64-linux/include/cuda/std/__memory/construct_at.h)
            function template "void stdgpu::destroy_at(T *)" (declared at line 722)
            argument types are: (thrust::THRUST_200500_860_NS::pair<const open3d::utility::MiniVec<short, 5>, open3d::core::buf_index_t> *)
      destroy_at(p);
      ^
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 24.04
- Python version: 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
- System architecture: x64
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 13.2.0 / clang 18.1.3
```

**Comment by Tiqo01** [comment]
I successfully compiled by modifying the file `stdgpu/include/stdgpu/impl/memory_detail.h,` replacing `destroy_at(p);` with `stdgpu::destroy_at(p);` and `forward<Args>` with `stdgpu::forward<Args>(args) `to avoid ambiguity.
