### PR TITLE
Changed usage of TensorFlow Status API

### PR DESCRIPTION
**Pull request by NobuoTsukamoto**
## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

In TensorFlow 2.11 and later, `tsensorflow::Status::OK()` has been removed.
This causes build errors.
Changing to `tensorflow::Status()` will maintain compatibility with previous versions and fix build errors.

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

If not corrected, the following build error will occur with TensorFlow v2.12.
```bash
error: 'OK' is not a member of 'tsl::Status'
  150 |             return Status::OK();
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6091)

### CODE REVIEW

**Comment by ssheorey** [comment]
Thanks, @NobuoTsukamoto.
@benjaminum This change works with the current Tensorflow 2.8 as well.

**Review by ssheorey — APPROVED** [review]
