### ISSUE TITLE
AttributeError: module 'open3d.cpu.pybind.geometry' has no attribute 'estimate_normals'Summarize the issue and your environments (e.g., "Cannot compile on Ubuntu 20.04 with OpenBLAS")

### ISSUE THREAD

**Issue by nn18339193656** [isl-org/Open3D#6370]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Steps to reproduce the issue

The problematic statement is open3d.geometry.estimate_normals(pcd,search_param=open3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))

### Error message

```shell
D:\Anaconda3\python.exe "F:\wangluo\Projection correction\PFH.py" 
Traceback (most recent call last):
  File "F:\wangluo\Projection correction\PFH.py", line 7, in <module>
    open3d.geometry.estimate_normals(pcd, search_param=open3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))
AttributeError: module 'open3d.cpu.pybind.geometry' has no attribute 'estimate_normals'

Process finished with exit code 1
```

### Open3D, Python and System information

```markdown
- Operating system:Windows 11 64-bit
- Python version: Python 3.7 
- Open3D version: 0.15.1
- System architecture: x86 
- Is this a remote workstation?:  no
- How did you install Open3D?: pip 
- Compiler version (if built from source): gcc 7.5 / clang 7.0
```

### Additional information

![微信图片_20230914183251](https://github.com/isl-org/Open3D/assets/145009712/3ca49881-07ea-4a4b-9028-28c255de432e)

**Comment by saurabheights** [comment]
Try
`
pcl.estimate_normals(KDTreeSearchParamHybrid(radius=0.05, max_nn=30))
`

See http://www.open3d.org/docs/0.15.1/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.estimate_normals

Make sure you use documentation of right open3d version

The `open3d.geometry.estimate_normals` is from older Open3D version 0.7.0.
