### ISSUE TITLE
"Web visualizer" requires `tensorboard` and fails on `ImportError` from `open3d.ml.vis`

### ISSUE THREAD

**Issue by jolastar** [isl-org/Open3D#4384]
**Description**

The `draw` function from `open3d.web_visualizer` fails in version 0.14.1 - first on a `ModuleNotFoundError` when `tensorboard` is not installed, then an `ImportError` from `open3d.ml.vis` if `tensorboard` is installed. 

**How to reproduce**

1. Create Python 3.9 conda environment with JupyterLab
2. Install open3d version 0.14.1 either with conda or with pip
3. Create a Jupyter notebook and enter the following:

```python
import open3d as o3d
from open3d.web_visualizer import draw
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()
draw([mesh])
```

4. If tensorboard is not installed, get `ModuleNotFoundError: No module named 'tensorboard'`
5. Install `tensorboard` with pip
6. Rerun the notebook, get `ImportError: cannot import name 'Colormap' from 'open3d.ml.vis'`

**Expected behavior**

The same code worked in version 0.13.0.

**Environment:**

- Operating system: Windows 10 64-bit
- Python version: Python 3.9
- Open3D version: 0.14.1
- Same issue with conda and pip installation

**Additional context**

From what I understand, the following happens:
* `web_analyzer.py`:

https://github.com/isl-org/Open3D/blob/4dea5bebba34abea39dae6e11bb54e6ff320d6cf/python/open3d/web_visualizer.py#L34

* `visualization/async_event_loop.py`:

https://github.com/isl-org/Open3D/blob/4dea5bebba34abea39dae6e11bb54e6ff320d6cf/python/open3d/visualization/async_event_loop.py#L74

* `visualization/tensorboard_plugin/util.py`:
 
https://github.com/isl-org/Open3D/blob/4dea5bebba34abea39dae6e11bb54e6ff320d6cf/python/open3d/visualization/tensorboard_plugin/util.py#L34-L42

* `ml/vis.py`:

https://github.com/isl-org/Open3D/blob/4dea5bebba34abea39dae6e11bb54e6ff320d6cf/python/open3d/ml/vis.py#L30-L34

* `open3d.ml.vis` does not define anything because `_build_config['BUNDLE_OPEN3D_ML']` is `False`

Here are all the contents of `o3d._build_config`:

```python

{'BUILD_TENSORFLOW_OPS': False,
 'BUILD_PYTORCH_OPS': False,
 'BUILD_CUDA_MODULE': False,
 'BUILD_AZURE_KINECT': True,
 'BUILD_LIBREALSENSE': True,
 'BUILD_SHARED_LIBS': False,
 'BUILD_GUI': True,
 'ENABLE_HEADLESS_RENDERING': False,
 'BUILD_JUPYTER_EXTENSION': True,
 'BUNDLE_OPEN3D_ML': False,
 'GLIBCXX_USE_CXX11_ABI': False,
 'CMAKE_BUILD_TYPE': 'Release',
 'CUDA_VERSION': '',
 'CUDA_GENCODES': '',
 'Tensorflow_VERSION': '',
 'Pytorch_VERSION': '',
 'WITH_OPENMP': True,
 'WITH_FAISS': False}
 ```

**Comment by yxlao** [comment]
@jolastar thanks for the detailed stack trace. Very informative. This issue may affect both Windows and macOS as the ML ops are not supported.

I would refer this to @ssheorey . Shall we make sure that the TensorBoard imports if ML ops are not bundled, or could we make sure they can coexist?

Before this is fixed properly, you can find your Open3D installation directory (e.g. by `python -c "import open3d; print(open3d)"`) and simply comment out all TensorBoard-related code.

**Comment by ssheorey** [comment]
@jolastar thanks for reporting this and the detailed debugging. For now, please remove 

https://github.com/isl-org/Open3D/blob/4dea5bebba34abea39dae6e11bb54e6ff320d6cf/python/open3d/visualization/async_event_loop.py#L74

This is unused and will let you use the web visualizer without tensorboard. You can either remove this from the source code and rebuild the Python wheel, or directly edit the installed wheel from the location `pip show open3d`.

I'll create a fix PR after some more testing on Windows.

**Comment by MOstanin** [comment]
@ssheorey 
The line deleting  
 from open3d.visualization.tensorboard_plugin.util import _log 
don't solve the whole problem.

There is still the error: 
ImportError: cannot import name 'Colormap' from 'open3d.ml.vis'

**Comment by pgutjahr** [comment]
Hi @ssheorey, had the same problem. 
Good news: latest dev build (c91e0a7) does not reproduce the import error anymore (cannot import name 'Colormap' from 'open3d.ml.vis'). 

was wondering though why the build does not support tensorflow and pytorch; is that excepted?
_python -c "import open3d.ml.torch as ml3d"_ and _python -c "import open3d.ml.tf as ml3d"_ both return the "not buildt with.." exception.

**Comment by ssheorey** [comment]
@pgutjahr Open3D wheel on Windows does not yet support TensorFlow and PyTorch. We have open issues for that. Contributions welcome!
