### ISSUE TITLE
Summarize the issue and your environments (e.g., "Cannot compile on Ubuntu 20.04 with OpenBLAS")

### ISSUE THREAD

**Issue by dbdxnuliba** [isl-org/Open3D#5775]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone --recursive https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I build Open3D (on Ubuntu 20.04, IntelNUC without cuda) with:
```
mkdir build
cd build
cmake -DBUILD_EIGEN3=ON -DBUILD_GLEW=ON -DBUILD_GLFW=ON -DBUILD_JSONCPP=ON -DBUILD_PNG=ON -DGLIBCXX_USE_CXX11_ABI=ON -DPYTHON_EXECUTABLE=/usr/bin/python -DBUILD_UNIT_TESTS=OFF  -DCMAKE_INSTALL_PREFIX=/home/robot/open3d/dist ..
make -j4
```

### Error message

```shell
[ 83%] Building CXX object cpp/pybind/CMakeFiles/pybind.dir/camera/camera.cpp.o
[ 83%] Building CXX object examples/cpp/CMakeFiles/CameraPoseTrajectory.dir/CameraPoseTrajectory.cpp.o
/usr/bin/ld: ../../embree/lib/libembree3.a(bvh4_factory.cpp.o): in function `embree::BVH4Factory::selectIntersectors(int)':
bvh4_factory.cpp:(.text+0x2943): undefined reference to `embree::avx::BVH4OBBVirtualCurveIntersector8Hybrid()'
/usr/bin/ld: bvh4_factory.cpp:(.text+0x295d): undefined reference to `embree::avx::BVH4OBBVirtualCurveIntersector8HybridMB()'
/usr/bin/ld: bvh4_factory.cpp:(.text+0x296b): undefined reference to `embree::avx::BVH4OBBVirtualCurveIntersectorRobust8Hybrid()'
/usr/bin/ld: bvh4_factory.cpp:(.text+0x2979): undefined reference to `embree::avx::BVH4OBBVirtualCurveIntersectorRobust8HybridMB()'
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04 /
- Python version: Python 3.8.10
- Open3D version: output from python: `print(open3d.__version__)`
- System architecture: x86
- Is this a remote workstation? no
- How did you install Open3D?:/ build from source
- Compiler version (if built from source): gcc 9.4.0 / clang 16.0.0
```
