### PR TITLE
Check for support of CUDA Memory Pools at runtime (#4679)

### LINKED ISSUE #4679: CUDA runtime error - open3D v0.14.1
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

With the following configuration:
- Ubuntu "18.04.6 LTS (Bionic Beaver)"
- gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- nvcc version: Cuda compilation tools, release 11.6, V11.6.55
- cmake version 3.22.2

I got a runtime error, running the DenseSlam.cpp when I set `"--device CUDA:0"` but everything works fine when I use `"--device CPU:0"`

The error is the following 
`[Open3D INFO] Using device: CUDA:0
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Open3D Error] (void open3d::core::__OPEN3D_CUDA_CHECK(cudaError_t, const char*, int)) /home/ubuntu/Work/Projects/handheld-scanning-prototype/Open3DBox/build/open3d/src/external_open3d/cpp/open3d/core/CUDAUtils.cpp:301: /home/ubuntu/Work/Projects/handheld-scanning-prototype/Open3DBox/build/open3d/src/external_open3d/cpp/open3d/core/MemoryManagerCUDA.cpp:43 CUDA runtime error: operation not supported`

I do not understand what is the issue, since testing my cuda install I've run the `deviceQuery` cuda application which outputs me the following
`bin/x86_64/linux/release/deviceQuery Starting...`
`CUDA Device Query (Runtime API) version (CUDART static linking)`
`Detected 1 CUDA Capable device(s)`
`Device 0: "Quadro M1000M"`
`  CUDA Driver Version / Runtime Version          11.6 / 11.6`
`  .... `
`  deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.6, CUDA Runtime Version = 11.6, NumDevs = 1
Result = PASS`

Could you please provide any support to solve my issue?

Also joining my cmake file to build open3D
```
# Option 1: Use ExternalProject_Add, as shown in this CMake example.
# Option 2: Install Open3D first and use find_package, see
#           http://www.open3d.org/docs/release/cpp_project.html for details.
include(ExternalProject)
ExternalProject_Add(
    external_open3d
    PREFIX open3d
    GIT_REPOSITORY https://github.com/intel-isl/Open3D.git
    GIT_TAG v0.14.1
    GIT_SHALLOW ON
    UPDATE_COMMAND ""
    # Check out https://github.com/intel-isl/Open3D/blob/master/CMakeLists.txt
    # For the full list of available options.
    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
        -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
        -DGLIBCXX_USE_CXX11_ABI=${GLIBCXX_USE_CXX11_ABI}
        -DSTATIC_WINDOWS_RUNTIME=${STATIC_WINDOWS_RUNTIME}
        -DBUILD_SHARED_LIBS=ON
        -DBUILD_PYTHON_MODULE=OFF
        -DBUILD_EXAMPLES=OFF
        -DBUILD_WEBRTC=OFF
        -DBUILD_CUDA_MODULE=ON
)
```

### Steps to reproduce the bug

```python
In a ubuntu 18.04.6 linux distribution with a machine supporting cuda
Install cuda 11.6
Use open3D external cmake add external 
Run the example DenseSLAM with flag "--device CUDA:0"
```

### Error message

`[Open3D INFO] Using device: CUDA:0
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Open3D Error] (void open3d::core::__OPEN3D_CUDA_CHECK(cudaError_t, const char*, int)) /home/ubuntu/Work/Projects/handheld-scanning-prototype/Open3DBox/build/open3d/src/external_open3d/cpp/open3d/core/CUDAUtils.cpp:301: /home/ubuntu/Work/Projects/handheld-scanning-prototype/Open3DBox/build/open3d/src/external_open3d/cpp/open3d/core/MemoryManagerCUDA.cpp:43 CUDA runtime error: operation not supported`

### Expected behavior

Running DenseSLAM without crashing it is the case when running with the flag "--device CPU:0"

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 18.04.6
- Open3D version: 0.14.1
- System type: 64 bit machine
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 7.5
```

### Additional information

image

### PR DESCRIPTION
**Pull request by ao2**
## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #4679
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

Some CUDA GPUs, like the Quadro M3000M don't support Memory Pools operations like `cudaMallocAsync`/`cudaFreeAsync` even on driver versions newer than 11020, and this can result in errors like:

```
CUDA runtime error: operation not supported
```

So check for support at runtime instead of compile time.

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

A new `core::cuda::SupportsMemoryPools()` helper function is added, and it is used to decide whether to use `cudaMallocAsync`/`cudaMallocFree` or not.

Initially I though about adding this to the Device class (e.g. `Device::IsCUDAMemoryPoolsSupported()`), but this is quite CUDA specific so I decided not to.

Please note that currently I cannot test the code on non-Quadro GPUs so I would like someone else to verify that it does not break already working cases.

Thanks,
Antonio

- - -
This change is [Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6440)

### CODE REVIEW

**Comment by benjaminum** [comment]
Thank you for this contribution! Please have a look at the checks. There are some problems with unknown identifiers `error C3861: 'cudaFreeAsync': identifier not found`.

**Comment by ao2** [comment]
I pushed an update with a compilation fix and I was able to build and run locally.

**Comment by ao2** [comment]
OK, in the latest version I kept the compile time check as well to be able to build with CUDA versions older than 11.2, apparently some CI jobs are using 11.0.3 https://github.com/isl-org/Open3D/blob/881ae76500708aec6d7d8ab070a92776334ce0cd/.github/workflows/windows.yml#L48

**Comment by ao2** [comment]
Pushed another update to also guard `cudaDevAttrMemoryPoolsSupported` behind cuda version >= 11.2

Hopefully this fixes the CI windows build issues with older cuda versions.

I have no clue about the failure in the `headless-docs` job tho, any suggestion?

Thanks, Antonio

**Comment by benjaminum** [comment]
> Pushed another update to also guard `cudaDevAttrMemoryPoolsSupported` behind cuda version >= 11.2
> 
> Hopefully this fixes the CI windows build issues with older cuda versions.
> 
> I have no clue about the failure in the `headless-docs` job tho, any suggestion?
> 
> Thanks, Antonio

Thanks! The `headless-docs` problem does not seem related to this PR

**Review by benjaminum — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6440#-:-Ni1PDDO39IaM0OG2xwH:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved
