### ISSUE TITLE
Summarize the issue and your environments (e.g., "Cannot compile on Ubuntu 20.04 with OpenBLAS")

### ISSUE THREAD

**Issue by FurlongRuss** [isl-org/Open3D#5240]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Steps to reproduce the issue

Download the binary for v0.15.1 from (for instance) https://github.com/isl-org/Open3D/releases/download/v0.15.1/open3d-devel-windows-amd64-0.15.1.zip
Extract zip file onto my PC.
Write a simple C++ console application in MSVC based on the tutorial. 
I can draw point spheres, boxes and point clouds.
I try to use the webRTC server and I get linker errors as below:

### Error message

```shell
error LNK2019: unresolved external symbol "public: static class std::shared_ptr<class open3d::visualization::webrtc_server::WebRTCWindowSystem> __cdecl open3d::visualization::webrtc_server::WebRTCWindowSystem::GetInstance(void)" (?GetInstance@WebRTCWindowSystem@webrtc_server@visualization@open3d@@SA?AV?$shared_ptr@VWebRTCWindowSystem@webrtc_server@visualization@open3d@@@std@@XZ) referenced in function main

error LNK2019: unresolved external symbol "public: void __cdecl open3d::visualization::webrtc_server::WebRTCWindowSystem::EnableWebRTC(void)" (?EnableWebRTC@WebRTCWindowSystem@webrtc_server@visualization@open3d@@QEAAXXZ) referenced in function main
```

### Open3D, Python and System information

```markdown
Open3D 0.15.1
Visual Studio 2022
Windows 10
```

### Additional information

I attempt to build from source.
I find that the CMakeList that BUILD_SHARED_LIBS is set to OFF. This isn't going to build the dll I downloaded.
I can set BUILD_SHARED_LIBS to ON, but now it doesn't download WebRTC.

(I can install Open3d 0.15.1 in python and the Web Visualizer works fine.)

I inspect the dll using dumpbin and I find that no webrtc related functions are exported.
