### ISSUE TITLE
"Utility" compile error under Windows 10

### ISSUE THREAD

**Issue by jsemeda** [isl-org/Open3D#1615]
I see that the library compiles under Windows 10. I am using Visual Studio 2019 to compile, not sure what is has been compiled with under Windows to pass. I am getting an error in "Utility" listed below
D:\Libraries\Open3D-master\3rdparty\fmt\include\fmt\core.h(977,9): error C2338: Cannot format argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#formatting-user-defined-types
1>  D:\Libraries\Open3D-master\3rdparty\fmt\include\fmt\core.h(974): message : while compiling class template member function 'int fmt::v6::internal::arg_mapper<Context>::map(...)'
1>          with
1>          [
1>              Context=fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char>>,char>
1>          ]
1>  D:\Libraries\Open3D-master\3rdparty\fmt\include\fmt\core.h(1174): message : see reference to function template instantiation 'int fmt::v6::internal::arg_mapper<Context>::map(...)' being compiled
1>          with
1>          [
1>              Context=fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char>>,char>

**Comment by syncle** [comment]
Do you mean compilation from source on Windows fails? [CI for Windows is passing](https://ci.appveyor.com/project/yxlao/open3d/branch/master). Consider cleaning-up 3rdparty dependency and retrying.

**Comment by jsemeda** [comment]
yes compiling from source under WIndows 10 with Visual Studio 2019 failed for me, error in "Utility" compiling console.cpp and the error is with the formatter template in core.h
I have downloaded the 3rd party packages and compiled them from source, so I am sure the problem is not from there.

**Comment by kmateti** [comment]
Hi @jsemeda, have you had any success to get past this issue?  I am also trying to compile v0.11.2 for a C++ application, and having compilation error related to fmt:  "Error C2338 don't know how to format the type, include fmt/ostream.h if it provides an operator<< that should be used" | utility	| C:\dev\Open3D\3rdparty\fmt\include\fmt\core.h | Line 493, and others.

**Comment by nitinkapgate** [comment]
Hi @jsemeda I am also having a similar issue on Older version (some commit after version 13). Were you able to resolve this issue? Do you have any clue @kmateti

**Comment by ssheorey** [comment]
@nitinkapgate Please share your environment details and the build (`cmake`) flags. Open3D builds with Visual Studio 2019 16.11.31911.196 in CI.
e.g.: https://github.com/isl-org/Open3D/runs/4487091084?check_suite_focus=true

**Comment by ssheorey** [comment]
Thanks for reporting back. If you still find this issue, please test with the latest Open3D `master` and open a new issue.
