### ISSUE TITLE
Summarize the issue and your environments (e.g., "Cannot compile on Ubuntu 20.04 with OpenBLAS")

### ISSUE THREAD

**Issue by paucarre** [isl-org/Open3D#5251]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I build Open3D (on Ubuntu 20.04, with CUDA 11.5) with:
```
mkdir build
cd build
~/cmake-3.23.0-rc4/bin/cmake .. -DBUILD_EXAMPLES=ON  -DBUILD_PYTHON_MODULE=ON -DBUILD_CUDA_MODULE=ON -DGLIBCXX_USE_CXX11_ABI=ONmake -j$(nproc)
```

### Error message

```shell
79%] Linking CXX executable ../../bin/Open3D/Open3D                                                                                                                                                      
/usr/bin/ld: ../../lib/Release/libOpen3D.a(NPPImage.cpp.o): in function `open3d::t::geometry::npp::RGBToGray(open3d::core::Tensor const&, open3d::core::Tensor&)':                                         
NPPImage.cpp:(.text+0x38a): undefined reference to `nppiRGBToGray_8u_C3C1R_Ctx'                                                                                                                            
/usr/bin/ld: NPPImage.cpp:(.text+0x443): undefined reference to `nppiRGBToGray_32f_C3C1R_Ctx'                                                                                                              
/usr/bin/ld: NPPImage.cpp:(.text+0x4ad): undefined reference to `nppiRGBToGray_16u_C3C1R_Ctx'                                                                                                              
/usr/bin/ld: ../../lib/Release/libOpen3D.a(NPPImage.cpp.o): in function `open3d::t::geometry::npp::Dilate(open3d::core::Tensor const&, open3d::core::Tensor&, int)':                                       
NPPImage.cpp:(.text+0x865): undefined reference to `nppiDilateBorder_8u_C1R_Ctx'                                                                                                                           
/usr/bin/ld: NPPImage.cpp:(.text+0x955): undefined reference to `nppiDilateBorder_8u_C3R_Ctx'                                                                                                              
/usr/bin/ld: NPPImage.cpp:(.text+0xa63): undefined reference to `nppiDilateBorder_16u_C4R_Ctx'                                                                                                             
/usr/bin/ld: NPPImage.cpp:(.text+0xb83): undefined reference to `nppiDilateBorder_32f_C4R_Ctx'                                                                                                             
/usr/bin/ld: NPPImage.cpp:(.text+0xc25): undefined reference to `nppiDilateBorder_8u_C4R_Ctx'
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04.3 LTS
- Python version: Python 3.8.10
- Open3D version: Latest in master branch. Hash: 55ded67ee758798ceb5e5ed6d875a18bafa86e62
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 7.5
```
