### ISSUE TITLE
Summarize the issue and your environments (e.g., "Cannot compile on Ubuntu 20.04 with OpenBLAS")

### ISSUE THREAD

**Issue by jiapei100** [isl-org/Open3D#5185]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I build Open3D (on Ubuntu 22.04, with CUDA 11.6) with:
```
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_CUDA_MODULE=OFF -DUSE_BLAS=ON -DBUILD_WEBRTC=OFF ..
make -j$(nproc)
```

### Error message

```shell
....../Open3D/cpp/open3d/visualization/gui/Window.cpp:1112:39: error: invalid conversion from ‘ImGuiID’ {aka ‘unsigned int’} to ‘const char*’ [-fpermissive]
 1112 |                 ImGui::IsPopupOpen(w->PopupId)) {
      |                                    ~~~^~~~~~~
      |                                       |
      |                                       ImGuiID {aka unsigned int}
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 22.04
- Python version: Python 3.10.4
- Open3D version: master branch of Open3D, of the day: 2022-06-13
- System architecture: x86
- Is this a remote workstation?: yes
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 11.2 / clang 14.0
```

### Additional information

Looks like: 

- Open3D is **NOT compatible** with the **NEWest** imgui (branch master of the day 2022-06-13)
- It may have something to do with this pull request [https://github.com/isl-org/Open3D/pull/4844](https://github.com/isl-org/Open3D/pull/4844)

**Comment by brad-colbert** [comment]
Same problem on Ubuntu 22.04 built and running on Arm64.
Just adding that it's consistent across architectures.

**Comment by brad-colbert** [comment]
Ok, my quick fix was to change the cpp/open3d/visualization/gui/CMakeLists.txt file.  Lines 62, 63.
I added:

`else()
    target_sources(GUI PRIVATE
        NativeLinux.cpp
    )

    set_source_files_properties(Window.cpp Combobox.cpp PROPERTIES COMPILE_OPTIONS "-Wno-error;-fpermissive")
endif()
`
