### ISSUE TITLE
Errors occur when Open3D library is linked together with other libraries, e.g. gflags, opencv

### ISSUE THREAD

**Issue by bing-jian** [isl-org/Open3D#2286]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
Errors occur when Open3D library is linked together with other libraries, e.g. gflags, opencv
**To Reproduce**

Please see 
https://github.com/bing-jian/open3d_test

**Expected behavior**
The code should compile and work on major platforms including Windows, macOS and linux.

**Environment (please complete the following information):**
- Operating system:
  OSX 10.15, Ubuntu 16.04 and 18.04, Windows 10 64-bit
- Open3D version:  
  0.10.0
- Is this remote workstation?: 
 no
- How did you install Open3D?:
 build from source
- Compiler version (if built from source):
 gcc 7.5, clang 11.0

**Additional context**
Same code also worked on Windows 10.

**Comment by bing-jian** [comment]
*** Updates: Same code (well, almost same) and CMakeLists.txt worked when using Open3D 0.9.0 ***

https://github.com/bing-jian/open3d_test/tree/master/open3d_0.9.0_test

**Comment by MrGoort** [comment]
I have the same problem in Ubuntu 16 and 18 with libraries like boost and gtsam. I can work with Open3D v0.8.0 without any issues, but was trying to update to the latest version.

This is some of the linking errors that I am getting:

```
In function `xxxxxxx(int, char**, std::vector<long double, std::allocator<long double> >&, std::vector<int, std::allocator<int> >&, bool&, bool&, bool&, bool&, boost::filesystem::path&, boost::filesystem::path&, boost::filesystem::path&, boost::filesystem::path&, boost::filesystem::path&, boost::filesystem::path const&)':
main.cpp:(.text+0x2b004): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
main.cpp:(.text+0x2b669): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
main.cpp:(.text+0x2b9fa): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
main.cpp:(.text+0x2babc): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
main.cpp:(.text+0x2bc1c): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
main.cpp:(.text+0x2bcf4): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
CMakeFiles/.dir/src/main.cpp.o:main.cpp:(.text+0x2bd92): more undefined references to `boost::program_options::abstract_variables_map::operator[](std::string const&) const' follow
CMakeFiles/.dir/src/main.cpp.o: In function `gtsam::GenericValue<gtsam::Pose3>::print(std::string const&) const':
main.cpp:(.text._ZNK5gtsam12GenericValueINS_5Pose3EE5printERKSs[_ZNK5gtsam12GenericValueINS_5Pose3EE5printERKSs]+0x46): undefined reference to `gtsam::demangle(char const*)'
main.cpp:(.text._ZNK5gtsam12GenericValueINS_5Pose3EE5printERKSs[_ZNK5gtsam12GenericValueINS_5Pose3EE5printERKSs]+0x89): undefined reference to `gtsam::Pose3::print(std::string const&) const'
CMakeFiles/.dir/src/main.cpp.o: In function `gtsam::GenericValue<gtsam::imuBias::ConstantBias>::print(std::string const&) const':
main.cpp:(.text._ZNK5gtsam12GenericValueINS_7imuBias12ConstantBiasEE5printERKSs[_ZNK5gtsam12GenericValueINS_7imuBias12ConstantBiasEE5printERKSs]+0x46): undefined reference to `gtsam::demangle(char const*)'
main.cpp:(.text._ZNK5gtsam12GenericValueINS_7imuBias12ConstantBiasEE5printERKSs[_ZNK5gtsam12GenericValueINS_7imuBias12ConstantBiasEE5printERKSs]+0x89): undefined reference to `gtsam::imuBias::ConstantBias::print(std::string const&) const'
CMakeFiles/.dir/src/main.cpp.o: In function `boost::program_options::typed_value<bool, char>::xparse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&) const':
main.cpp:(.text._ZNK5boost15program_options11typed_valueIbcE6xparseERNS_3anyERKSt6vectorISsSaISsEE[_ZNK5boost15program_options11typed_valueIbcE6xparseERNS_3anyERKSt6vectorISsSaISsEE]+0x17): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool*, int)'
CMakeFiles/.dir/src/main.cpp.o: In function `boost::program_options::typed_value<std::string, char>::xparse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&) const':
main.cpp:(.text._ZNK5boost15program_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE[_ZNK5boost15program_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE]+0x17): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
CMakeFiles/.dir/src/main.cpp.o: In function `gtsam::GenericValue<Eigen::Matrix<double, 3, 1, 0, 3, 1> >::print(std::string const&) const':
```

**Comment by jkravanja** [comment]
I have a similar problem using Open3D and GFlags with the following message form linker:
    `undefined reference to google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)`
The error only seems to arise when defining a string flag using "DEFINE_string", however "DEFINE_bool", "DEFINE_double" and "DEFINE_int32" work without any problems.

Environment:
Ubuntu 18.04
Open3d 0.10.1.0
GFlags 2.2
g++ 7.5
cmake 3.17

**Comment by MrGoort** [comment]
Do we have any update for this bug???
I have tried with the new version of Open3D 0.11, but I still have the same linking problems

**Comment by jkravanja** [comment]
No, didn't manage to solve it.

**Comment by yankailab** [comment]
Ubuntu 20.04
Open3D 0.11.0
OpenCV 4.3.0

also met the undefined references issue with linker

**Comment by hos-b** [comment]
Ubuntu 20.04
Open3D 0.11.0
causes `undefined reference` linker error for :
- OpenCV 4.2
- ROS Noetic
- CARLA simulator 0.9.9
as soon as I try to link Open3D libraries, everything else fails to link.

**Comment by MrGoort** [comment]
I tried to do that, but unfortunately got a building error now:

/usr/local/include/open3d/utility/Console.h:40:10: fatal error: fmt/format.h: No such file or directory
 #include <fmt/format.h>
          ^~~~~~~~~~~~~~
compilation terminated.

really don't know what is the problem here, but puts me off to use this library.
There is also a compilation error in Line3D.h that can't believe how they haven't fixed it yet.

Anyway, if someone knows how to fix this problem, please leave a comment here

**Comment by hos-b** [comment]
> I tried to do that, but unfortunately got a building error now:
> 
> /usr/local/include/open3d/utility/Console.h:40:10: fatal error: fmt/format.h: No such file or directory
> #include <fmt/format.h>
> ^~~~~~~~~~~~~~
> compilation terminated.
> 
> really don't know what is the problem here, but puts me off to use this library.
> There is also a compilation error in Line3D.h that can't believe how they haven't fixed it yet.
> 
> Anyway, if someone knows how to fix this problem, please leave a comment here

that's most likely because you don't have [fmtlib](https://github.com/fmtlib/fmt). you should still get an error after building/installing it but an `undefined reference` not the one you got.

**Comment by hos-b** [comment]
I suspect that this is due to conflicts between any library that Open3D builds as a dependency (sort of invisibly) and anything else that uses those libraries. e.g. libfmt is built and used by Open3D. A ROS installation contains libqhull and therefor `${catkin_LIBRARIES}` might contain it. Maybe OpenCV fails because of Eigen dependencies. I hope the issue is solved in a future release. I had to move on to pcl for now.

**Comment by SoulProtagonist** [comment]
I was having a similar issue trying to link with Open3D v0.11.2. I found that setting -DGLIBCXX_USE_CXX11_ABI=ON when building Open3D fixed the linker errors for me.

**Comment by lwohlhart** [comment]
> I suspect that this is due to conflicts between any library that Open3D builds as a dependency (sort of invisibly) and anything else that uses those libraries. e.g. Open3D builds and uses libfmt and libqhull. A full ROS installation includes libqhull and therefor `${catkin_LIBRARIES}` might contain it. Maybe OpenCV fails because of Eigen dependencies. I hope the issue is solved in a future release. I had to move on to pcl for now.

I'm basically stuck with the same issue and I'd really like to move on (past the PCL era) 
Do you have any updates on the linking problem?

**Comment by hos-b** [comment]
> I'm basically stuck with the same issue and I'd really like to move on (past the PCL era)
> Do you have any updates on the linking problem? @hos-b
Unfortunately not. I haven't tried SoulProtagonist's solution either. I got what I wanted out of PCL to some extend and moved on. I got as far as this [stackoverflow question](https://pcl.readthedocs.io/projects/tutorials/en/latest/cloud_viewer.html#cloud-viewer) before giving up. It kinda describes our problem and the comments allegedly lead to a solution. What we're looking for is "pre-linking" Open3D with its dependencies, and then linking against our own. If you succeed, let me know.

**Comment by lwohlhart** [comment]
I guess I just got it to link properly by compiling Open3D as suggest in 
https://github.com/ntnu-arl/open3d_ros#open3d

**Comment by hos-b** [comment]
the flag seems to resolve the issue. I didn't really test the library but it linked just fine with Eigen, OpenCV, ROS, yaml-cpp and CARLA.

**Comment by TeddybearCrisis** [comment]
can canform linking issue exists without specific cmake options
proposals from @SoulProtagonist and @lwohlhart work with versions **0.11.2** and **0.12.0**
`cmake -DGLIBCXX_USE_CXX11_ABI=ON ..`

**Comment by ssheorey** [comment]
Thanks @bing-jian,  @SoulProtagonist and other reporters. We have made the new CXX11_ABI as the default option so you should not need to explicitly specify this any more.

**Comment by QuentinTorg** [comment]
For anyone having this error again, the default behavior regressed with [this PR](https://github.com/isl-org/Open3D/commit/336509be44a6b04782ed549b509899f1c49ba895#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR71) 

Default behavior now sets `BUILD_SYCL_MODULE=OFF` and `GLIBCXX_USE_CXX11_ABI=OFF`. I don't immediately see a reason that the default `GLIBCXX_USE_CXX11_ABI` value couldn't remain ON

@ssheorey this issue should probably be re-opened
